version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    groups:
      eslint:
        patterns:
          - '*eslint*'
  - package-ecosystem: cargo
    directory: 'wasm/'
    schedule:
      interval: weekly
      day: sunday
