root: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - xo
  - xo-typescript
  - plugin:unicorn/recommended
  - prettier
plugins:
  - eslint-plugin-tsdoc
parserOptions:
  jsx: false
  ecmaFeatures:
    jsx: false
rules:
  no-return-assign:
    - error
    - except-parens
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
  import/consistent-type-specifier-style:
    - warn
    - prefer-top-level
  import/order:
    - warn
    - groups:
        - external
        - [parent, sibling]
        - index
        - type
      newlines-between: always
      alphabetize:
        order: asc
  import/no-cycle:
    - warn
    - ignoreExternal: true
  import/no-unresolved:
    - error
    - ignore: ['^#']
  tsdoc/syntax: warn
  unicorn/custom-error-definition: error
  unicorn/prevent-abbreviations: off
  unicorn/switch-case-braces:
    - warn
    - avoid
settings:
  import/resolver:
    typescript: true
reportUnusedDisableDirectives: true
ignorePatterns:
  - dist/
